### ISSUE TITLE
Server always crashing

### ISSUE THREAD

**Issue by mkukiro** [Eugleo/magic-racket#118]
## Environment
- OS: Fedora Linux
- OS Version: 38
- VS Code Version: 1.80.1 (Installed using `dnf`)
- Racket version 7.4
- Racket Langserver checksum: `[none]`
- Magic Racket version: v0.6.6

## Error message
```
[Info  - 10:12:03 AM] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   /home/picto/.racket/7.4/collects
   /usr/share/racket/collects
   ... [159 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   module-path-index-resolve
   [repeats 1 more time]
   module-declared?
[Error - 10:12:04 AM] Connection to server got closed. Server will not be restarted.
```

## Additional context
There is also an error message that says "Language server crashed 5 times in the last 3 minutes, will not be restarted" or something like that ![](https://nukocities.neocities.org/nuko/react/cat19.gif)

**Comment by mkukiro** [comment]
Turns out I am dumb and I haven't installed the server ![](https://nukocities.neocities.org/nuko/react/cat339.gif)

**Comment by BranLiang** [comment]
In case if you are still wondering. You should run `raco pkg install racket-langserver` after/before install extension `Magic Racket`
