### ISSUE TITLE
No hover information and jump to definition

### ISSUE THREAD

**Issue by migraine-user** [Eugleo/magic-racket#129]
## Environment
- OS: EndeavorOS
- OS Version: arch linux, Kernel: 6.9.8-arch1-1 
- VS Code Version: 1.91.1-1
- Racket version: 8.13 [cs]
- Racket Langserver checksum: 140d94e7d64dd861bb2bfccc989d91382c4c8d8e
- Magic Racket version: 0.6.7

## Error message
N/A

## Additional context
Strangely, everything else seems to work fine, including autocomplete and error underlining. Nothing shows up on hover.

**Comment by jryans** [comment]
Hmm, curious! Just to double check, what are you expecting to see when hovering?

It might be worth changing Magic Racket’s language server verbosity setting in VS Code and then checking messages in the Output tab to look for any issues.

**Comment by jryans** [comment]
If you are able to share an example file / project, that may help as well.

**Comment by migraine-user** [comment]
> Hmm, curious! Just to double check, what are you expecting to see when hovering?

I assumed that there would be some documentation or definition for that symbol to pop up on hover. It seems like the error messages (red underline) show up on hover though. `Go to Definition` and `Go to References` fail to find anything. Here is the screenshot of the code I was working with.
![image](https://github.com/user-attachments/assets/cf700cc2-3798-4ca9-a130-f1f7aded13ad)
I expected that if I call `Go to Definition` or `Go to References` on `atom?` it would show the other occurrences. It fails to find anything.

> It might be worth changing Magic Racket’s language server verbosity setting in VS Code and then checking messages in the Output tab to look for any issues.

Could you tell me how I can change the verbosity settings? I've tried looking there before, but this is the only output I get:
```
Magic Racket environment info

os.arch:            x64
os.platform:        linux
os.release:         6.9.9-arch1-1
os.version:         #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000
process.version:    v20.9.0
vscode.env.appHost: desktop
vscode.env.appName: Visual Studio Code
vscode.env.shell:   /usr/bin/bash
```

**Comment by jryans** [comment]
> I assumed that there would be some documentation or definition for that symbol to pop up on hover. It seems like the error messages (red underline) show up on hover though. `Go to Definition` and `Go to References` fail to find anything. 

Okay, thanks for clarifying. Yes, those features should work, and I can confirm they work here in my own projects.

> Here is the screenshot of the code I was working with. 

Could you attach the actual file or link to a repo if it's in one? I'd like to test that source file so we are working with the same content, and I don't want to re-type it from a screenshot... 😜 

> Could you tell me how I can change the verbosity settings? I've tried looking there before, but this is the only output I get:

Sure, it's the setting in VS Code's Magic Racket settings called "Trace: Server". It defaults to "off". Try setting to "verbose" while we debug this issue. It should create a _new_ output category called "Racket Language Client" (which is separate from just "Racket" where you found the environment info above).

**Comment by migraine-user** [comment]
> > I assumed that there would be some documentation or definition for that symbol to pop up on hover. It seems like the error messages (red underline) show up on hover though. `Go to Definition` and `Go to References` fail to find anything.
> 
> Okay, thanks for clarifying. Yes, those features should work, and I can confirm they work here in my own projects.
> 
> > Here is the screenshot of the code I was working with.
> 
> Could you attach the actual file or link to a repo if it's in one? I'd like to test that source file so we are working with the same content, and I don't want to re-type it from a screenshot... 😜
> 
> > Could you tell me how I can change the verbosity settings? I've tried looking there before, but this is the only output I get:
> 
> Sure, it's the setting in VS Code's Magic Racket settings called "Trace: Server". It defaults to "off". Try setting to "verbose" while we debug this issue. It should create a _new_ output category called "Racket Language Client" (which is separate from just "Racket" where you found the environment info above).

I can't quite reproduce what caused the original issue I had, but that issue is gone. There was a different bug where I could not insert parens into an .rkt file, which was resolved after reloading the window. Sorry for the false alarm.
