### ISSUE TITLE
Doesn't work with other #langs

### ISSUE THREAD

**Issue by EmmanuelOga** [Eugleo/magic-racket#13]
Hi, I'm trying to use Magic Racket with https://github.com/mwand/eopl3, but it seems it does not support other #langs out of the box, is this right?

Thanks!

Opening test-all.rkt:

Terminal Error output;
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\emman\workspace\scheme\eopl3> racket
Welcome to Racket v7.7.
> all.rkt"))
; all.rkt: undefined;
;  cannot reference an identifier before its definition
;   in module: top-level
; [,bt for context]
>
```

Error output:
```
Caught exn:
current-load-relative-directory: path is not a complete path
  path: c%3A/Users/emman/workspace/scheme/eopl3/

Caught exn in request "textDocument/documentSymbol"
hash-ref: no value found for key
  key: 'file:///c%3A/Users/emman/workspace/scheme/eopl3/test-all.rkt

[Error - 4:36:09 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
```

**Comment by Eugleo** [comment]
Hey, it does not — at lesst the syntax highlighting. The LSP features (e.g. hover info, jump to definition) could theoretically work, and I’m actually interested whether they do or not. Could you please test it out?

**Comment by Eugleo** [comment]
Also, could you please tell me how exactly to reproduce these errors? Is it something like `raco pkg install eopl` and then opening a blank file with only something like `#lang eopl` on the top?

**Comment by Eugleo** [comment]
If I install `eopl` with `raco pkg install eopl`, I'm able to run the `test-all.rkt` file by pressing the green triangle button without any problem. Could you try to do this and report the results?

However, there _are_ some weird errors regarding hover info and outline information, I'll look at them more closely tomorrow.

**Comment by EmmanuelOga** [comment]
I suspect it may have something to do with Windows paths since it looks like:

`file:///c%3A/Users/emman/workspace/scheme/eopl3/test-all.rkt`

should be: 

`file:///c:/Users/emman/workspace/scheme/eopl3/test-all.rkt`

In any case this is what I did:

* Installed Racket (normal, not CS)
* Open test-all.rkt in Dr Racket. Run it, passes all the tests and goes to the REPL.
* I can also open an individual .scm file and it just works.

Now on VS Code:
* Install Magic Racket, open test-all.rkt.
* Try to run a REPL: fails with the errors pasted above.
* I ran `rack pkg install eopl` to see if it made a difference, but it is the same thing.

Again, I suspect it is a Windows 10 problem.

**Comment by whitetigle** [comment]
Related error on windows 10 with latest version (I guess)

```
[Error - 17:19:53] Request textDocument/documentHighlight failed.
  Message: internal error in method "textDocument/documentHighlight"
  Code: -32603 
Caught exn in request "textDocument/hover"
hash-ref: no value found for key
  key: 'file:///d%3A/test/test.rkt
```

**Comment by Eugleo** [comment]
@whitetigle Thanks for the details, indeed seems to be an issue with the paths. Could you please test if _running_ the file works? That can be done by pressing the green triangle, or alternatively running the `Run file in terminal` command.

**Comment by whitetigle** [comment]
@Eugleo nope it does not work: 

```
open-input-file: cannot open input file
  path: D:\test\'d:\test\test.rkt'
  system error: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.; errid=123
```

**Comment by Eugleo** [comment]
Thanks. So it was trying tu run `racket 'd:\test\test.rkt'`?

**Comment by whitetigle** [comment]
yes

**Comment by Eugleo** [comment]
Sure, same here :-D 

But wait; you’re saying that Magic Racket is running `racket 'd:\test\test.rkt'`, which **doesn’t** work, it throws the “invalid file” error. But manually running `racket 'd:\test\test.rkt'` works?

**Comment by whitetigle** [comment]
Sorry. 
From a terminal: 

- running `racket d:\test\test.rkt` (no quotes) works 
- running `racket 'd:\test\test.rkt'` (quotes) does not.

If I read the error message, it seems Magic Racket is trying to run the path with quotes which eventually leads to an error. (If I understand correctly)

**Comment by Eugleo** [comment]
Oh, I missed the quotes! Could be that windows doesn’t support single quotes, unlike unix. What if you run it with double quotes?

**Comment by whitetigle** [comment]
yes no single/double quotes on windows it seems 👍

**Comment by Eugleo** [comment]
I actually thought that double quotes should work even on Windows, isn't that the case?

**Comment by Eugleo** [comment]
Sorry that I'm bombarding you with so many questions, but which shell are you using in the integrated terminal? 

As per [this issue](https://github.com/Microsoft/vscode/issues/19746), PowerShell should be the default, and it seems that PowerShell **does** indeed support single quotes. Could you confirm that you are **not** using PowerShell? It should be configured in `terminal.integrated.shell.windows`.

**Comment by whitetigle** [comment]
Ok.
So my default shell was command. I switched to PowerShell and confirm that now quotes are working.
So I can send the whole file using Magic Racket's play button and it works fine.
I can also start the REPL and it's fine.


The only remaining issue is Hover in the file which leads to aforementionned error: 

```
[Error - 09:18:47] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
Caught exn in request "textDocument/hover"
hash-ref: no value found for key
  key: 'file:///d%3A/test/test.rkt
```

**Comment by Eugleo** [comment]
Should be fixed in v0.5.6 (will be live any moment now). I still encounter some issues with the LSP, but only with specific files, which leads me to think it's an issue with the server itself. I'll investigate.

**Comment by whitetigle** [comment]
Thanks! And bravo for this extension. It rocks 👍

**Comment by whitetigle** [comment]
Ok, last update corrected the pb. 👏 

Don't know if it can help but here are my logs regarding language server: ```

[Info  - 15:26:47] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\whitetigle\AppData\Roaming\Racket\7.6\collects
   D:\Racket\collects
   ... [177 additional linked and package directories]
[Info  - 15:26:48] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\whitetigle\AppData\Roaming\Racket\7.6\collects
   D:\Racket\collects
   ... [177 additional linked and package directories]
[Error - 15:26:48] Connection to server got closed. Server will not be restarted.
```

**Comment by Eugleo** [comment]
Didn’t see those errors yet. Make sure that racket is on your path, that racket-langserver is installed with raco and also restart VS Code. Sometimes PowerShell messes up the PATH...

**Comment by whitetigle** [comment]
ok I will check. Thanks!

**Comment by whitetigle** [comment]
Ok. everything's fine now. Thanks 👍
