### ISSUE TITLE
custom #lang usage causes error vscode output flooding 

### ISSUE THREAD

**Issue by jshap70** [Eugleo/magic-racket#16]
In my case I am using `#lang pollen`.

I am met with the "A request has failed. See the output for more information" which continually pops up multiple times a second. Closing it does nothing as it just reopens. 

The actual output looks like: 
```racket
Caught exn in request "textDocument/documentSymbol"
get-lexer: '(#<procedure:scribble-inside-lexer> . #f)
  context...:
   /home/jshapiro/.racket/7.7/pkgs/racket-langserver/text-document.rkt:233:0: document-symbol
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/jshapiro/.racket/7.7/pkgs/racket-langserver/methods.rkt:26:0: process-message
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/jshapiro/.racket/7.7/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 11:28:29 AM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
....
```

Anyways, the highlighting actually works as I would like and it makes sense that hover symbol finding wouldn't work for 3rd party `#lang` definitions, but would it be possible to not enable the hover functions on non supported `#lang`'s because currently this output is incredibly annoying lol.

**Comment by jshap70** [comment]
note that there are similar message spam issues when you open files outside of the project directory like in `/tmp` when viewing a timeline diff or smth, but I might open a second issue to track that.

**Comment by Eugleo** [comment]
Will test, thanks for reporting! In the meantime, for pollen, you could try using my old extension [vscode-pollen](https://github.com/Eugleo/vscode-pollen).

**Comment by sammcf** [comment]
I'm having the same user experience & error message. In my case, it looks like the language server is being passed the #lang symbol character-by-character and attempting to resolve it for the cumulative list as each character is added. Once a valid #lang line is complete, the error stops for me. I dropped the full output in a [paste](https://pastebin.com/C6cJ0YRg) - this output is triggered in entirety by editing an empty .rkt file and typing #lang sicp on the first line. Once the line is complete, the package is loaded correctly and it all works perfectly!

**Comment by soapdog** [comment]
Same experience happening with `#lang at-exp racket`

```
Caught exn in request "textDocument/documentSymbol"
get-lexer: '(#<procedure:scribble-lexer> . #f)
  context...:
   C:\Users\andre\AppData\Roaming\Racket\7.7\pkgs\racket-langserver\text-document.rkt:242:0: document-symbol
   C:\Program Files (x86)\Racket\collects\racket\contract\private\arrow-val-first.rkt:486:18
   C:\Users\andre\AppData\Roaming\Racket\7.7\pkgs\racket-langserver\methods.rkt:26:0: process-message
   C:\Program Files (x86)\Racket\collects\racket\contract\private\arrow-val-first.rkt:486:18
   C:\Users\andre\AppData\Roaming\Racket\7.7\pkgs\racket-langserver\main.rkt:54:2: consume

[Error - 2:09:06 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
```

**Comment by Eugleo** [comment]
Thank you both for the reports! As this is more of a langserver issue, I’ll close this one and make a new one on their repo. I’ll mention you ther so you can keep up with the updates.
