### ISSUE TITLE
Language server fails to start on macOS due to missing library

### ISSUE THREAD

**Issue by dustypomerleau** [Eugleo/magic-racket#19]
Thanks for all your hard work on Magic Racket. 

Setup:
macOS 10.15.5
VS Code 1.46.1
Racket 7.7 installed via asdf
Magic Racket 0.5.6

Output after language server fails:
```
[Info  - 3:15:36 PM] Connection to server got closed. Server will restart.
ffi-lib: couldn't open "libintl.9.dylib" (dlopen(libintl.9.dylib, 6): image not found)
  context...:
   /Users/dustinpomerleau/.asdf/installs/racket/7.7/collects/ffi/unsafe.rkt:131:0: get-ffi-lib
   "/Users/dustinpomerleau/.asdf/installs/racket/7.7/share/pkgs/draw-lib/racket/draw/unsafe/glib.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   for-loop
   [repeats 1 more time]
   ...
```

**Comment by Eugleo** [comment]
Firstly: didn't know about `asdf`, cool! Concerning the error, I think `libintl` is missing from your system (or else not linked properly), i.e. not a Magic Racket problem, and I won't be able to help you with that, unfortunately. 

I tried to search for a solution, but the only thing I found is the following [SO post](https://stackoverflow.com/a/47387255/2421792), where they basically tell you to shut up and install Racket from the official distribution channel. To further debug the issue, you could try runnning 

```
locate libintl
``` 

or

```
find /usr -name libintl* -print 2>/dev/null
```

which could tell you whether `libintl` is in your machine (and thus Racket just can't find it), or whether it's not there at all. In either case, I wish you luck solving this issue! Let me know once you do, I'll close the issue in the meantime.

**Comment by dustypomerleau** [comment]
Thanks for replying. It appears the issue is with the version of `libintl`, not whethere it's installed. On macOS, `libintl` is not preinstalled, and is usually added by installing `gettext`. However, `brew install gettext` installs `libintl.8.dylib`, and Racket 7.7 [appears to mandate `libintl.9`](https://github.com/racket/racket/blob/4ad93bcca0a1b9399f029bec969011f2245548a5/racket/src/native-libs/install.rkt#L16). When I discovered this, I wasn't sure how to proceed, as I'm on the latest version of `gettext`, and  I don't see any way of installing `libintl.9.dylib` as a standalone library.

So I continued to dig, and found this comment on [a conda issue](https://github.com/conda/conda/issues/6183):
> The crux of all of these libintl.9.dylib-on-macOS problems dates back to early this year when the GNU gettext project distributed a broken source release which built a shared library called libintl.9.dylib when it should have been libintl.8.dylib. Rather than just saying "oops, it's too late now" they made the (IMHO unfortunate) decision to undo that change in a patch release.
>
> During that broken window (before I was aware it was broken) I rebuilt all of our R packages on all platforms against the latest version of R at the time.
>
> Then, for the AD 5 release we rebuilt everything based on the latest versions available at the time (very recently) so we are back to providing libintl.8.dylib instead. These new R packages on rdonnellyr are part of this mass-rebuild.

So it appears that `libintl.8` is really the latest version. Does that mean this is a bug in Racket? I'm happy to submit an issue there. I just find it strange that I am the only one experiencing this.

**Comment by Eugleo** [comment]
Wow, that goes deeper than I expected it to. From the conda it seems that yes, libintl.8 is the latest one. You can try opening an issue on Racket, they should at least be able to help you. Also, it seems that just [renaming the file could help](https://gis.stackexchange.com/questions/304705/libintl-9-dll-is-missing-when-trying-to-run-postgis-2-0-shapefile-and-dbf-load).

**Comment by dustypomerleau** [comment]
Thank you for your time. This may be as simple as a one-line PR on Racket, but I will ask first.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dustypomerleau** [comment]
Unfortunately, after some testing I have determined that the issue is related to asdf. I am still not sure exactly where the offending code is, but essentially Magic Racket must be looking for a path to the libraries that is overridden when `asdf.sh` runs and inserts its shims, so that Magic Racket can't 'see' the libraries. Interestingly, Racket from the command line works fine once the shell launches, so the issue seems to be that the language server launches first? For the moment I have reverted to using Homebrew Racket. Thanks again for your time.

**Comment by dqisme** [comment]
For the people who have the same issue here:

Please run the updating commands below AFTER installing by `asdf`. I tried them, and they can resolve this problem perfectly.

```
raco pkg update --auto racket-lib
raco pkg update --auto main-distribution
```
