### ISSUE TITLE
REPL Question

### ISSUE THREAD

**Issue by bthesorceror** [Eugleo/magic-racket#2]
Do you plan on adding REPL integration or will this extension be for only syntax highlighting?

**Comment by Eugleo** [comment]
It'd be great to add support for REPL eventually; as well as some other goodies from LSP, for example. I'm a bit bussy right now, but if you're interested, I'm open to PRs of any kind!

**Comment by Eugleo** [comment]
@bthesorceror Just to make a quick update, REPL support is coming in the next few days.

**Comment by Eugleo** [comment]
The REPL support has been added in the latest commit. The new version will be uploaded on the Marketplace today or tomorrow.
