### ISSUE TITLE
Missing #lang angers magic-racket, gives less than helpful output

### ISSUE THREAD

**Issue by jasonhemann** [Eugleo/magic-racket#22]
## Environment
- OS: [e.g. MacOS] OSX
- OS Version [e.g. Catalina] Catalina (10.15.5)
- VS Code Version [e.g. 1.46.1] 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
- Racket version [e.g. 7.7] v7.5
  - run: `racket -v`
- Racket Langserver checksum [e.g. 64c1827548089c97c56a53a90ef3d569deb0e6c2]
  - run: `raco pkg show --full-checksum racket-langserver`
Installation-wide:
 [none]
User-specific for installation "7.5":
 Package            Checksum                                  Source
 racket-langserver  01bc4ad03e449dfbe1852a141748c3d6121a1e75  catalog...e/racket-langserver.git
- Magic Racket version [e.g. 0.5.6] 0.5.6

## Error message
Please insert the error message you see in VS Code.

Caught exn in request "textDocument/documentSymbol"
get-lexer: 'before-lang-line
  context...:
   ./Racket/7.5/pkgs/racket-langserver/text-document.rkt:242:0: document-symbol
   ./Racket v7.5/collects/racket/contract/private/arrow-val-first.rkt:486:18
   ./Racket/7.5/pkgs/racket-langserver/methods.rkt:26:0: process-message
   ./Racket v7.5/collects/racket/contract/private/arrow-val-first.rkt:486:18
   ./Racket/7.5/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 8:38:35 AM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 

## Additional context

This was in a racket file missing the `#lang racket`. I feel like the error message could be more helpful.
Try with a blank, empty file, or a file filled just with a couple of newlines. 

--

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.

**Comment by Eugleo** [comment]
Thanks for the report! I thought about thiś and I think we should migrate this issue to the langserver repo; I could code around this in my extension, but I don’t think it’s a good idea to introduce special cases like that.

With that said, Ik´ll close this issue and open a new one on their repo and mention you there, so you can keep up.
