### ISSUE TITLE
internal error in method "textDocument/documentSymbol" Code: -32603

### ISSUE THREAD

**Issue by togna** [Eugleo/magic-racket#23]
## Environment
- OS: kubuntu
- OS Version 20.04
- VS Code Version 1.47.3
- Racket version 7.7
- Racket Langserver checksum 01bc4ad03e449dfbe1852a141748c3d6121a1e75
- Magic Racket version 0.5.6

## Error message
Caught exn in request "textDocument/documentSymbol"
get-lexer: 'before-lang-line
  context...:
   /home/tog/.racket/7.7/pkgs/racket-langserver/text-document.rkt:242:0: document-symbol
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/tog/.racket/7.7/pkgs/racket-langserver/methods.rkt:26:0: process-message
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/tog/.racket/7.7/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 9:06:19 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 

## Additional context
Happens basically every keystroke while I'm editing the file (had to change extension from .rkt to .txt)
[test.txt](https://github.com/Eugleo/magic-racket/files/4992519/test.txt)

---

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.

**Comment by Eugleo** [comment]
I think this might be because the file is missing a `#lang racket` (or #lang whatever) line. With the line added, I don't see any errors.

**Comment by togna** [comment]
Ah, I thought I had tried that but I guess I missed it. The error still happens if `#lang racket` is the second line (for example if you have `#!/usr/bin/racket` as the first line). Thanks for the help!

**Comment by Eugleo** [comment]
Sorry for the late response. If that’s the case, I think we should open an issue over at the langserver repo, because it doesn’t seem to have anything to do with Magic Racket itself. 

I’ll mention you once I create the issue on their repo.
