### ISSUE TITLE
Second step of the installation???

### ISSUE THREAD

**Issue by aelmazou** [Eugleo/magic-racket#25]
Hi

I personally don't find the second given step for the installation (to install `racket-langserver`) very clear. How do I run the command? It's clearly not in the regular terminal.

Thanks in advance for helping a newb out.

**Comment by shiwunan** [comment]
Navigate to the install directory of Racket and open a PowerShell window. add `.\` before pasting `raco pkg install racket-langserver`

**Comment by Grudairian** [comment]
Just wanted to say thanks, this helped me as well

**Comment by Eugleo** [comment]
@aelmazou Is your issue resolved? Can I close this?
