### ISSUE TITLE
Make editor ruler optional

### ISSUE THREAD

**Issue by micahcantor** [Eugleo/magic-racket#27]
Hi, this is a great extension and I appreciate the work you've done. My only issue is the extension adds a line down the middle of the editor on column 103. Here's a screenshot:

![MagicRacketLine](https://user-images.githubusercontent.com/42819290/97064964-08090600-1578-11eb-9d7f-280153420f90.png)

And with the extension disabled:

![RacketNoLIne](https://user-images.githubusercontent.com/42819290/97064972-13f4c800-1578-11eb-9086-64257c2dfbe7.png)
Is this the intended functionality? And if so, can a setting be added to remove it?

**Comment by micahcantor** [comment]
I realize now that this comes from the configuration default in the package.json
``` json
"configurationDefaults": {
      "[racket]": {
        "editor.rulers": [
          102
        ],
        "editor.wordSeparators": "()[]{}\",'`;#|"
      }
    },
```
I'm not very familiar with VSCode extension development, but is there a way that this could be moved to the general configuration instead so it can be disabled in setttings?

**Comment by Eugleo** [comment]
Hey! I can't test it rn, but I think it should be possible to just disable `editor.rulers` in VS Code settings (i.e. not Magic Racket section, but the general editor settings). It should also be possible to disable it for racket only, or set it to different values based on the language. The settings provided by Magic Racket should be just a configurable default.

Let me know if this works, I'll update the README to make this clearer.

**Comment by micahcantor** [comment]
Okay, you are right that this is possible to override by adding this to vscode settings.json:

``` json
"[racket]": {
        "editor.rulers": [],
    }
```

But that is not very obvious, so I agree that updating the README would be helpful, if you want to keep that setting in by default.
