### ISSUE TITLE
Unable to init server on WSL

### ISSUE THREAD

**Issue by jdan** [Eugleo/magic-racket#29]
## Environment
- OS: Windows via WSL
- OS Version: 10
- VS Code Version: 1.51.1
- Racket version: 7.2
- Racket Langserver: checksum 19953f6afda5f8f6b539e88d0c6be57599a8a11f
- Magic Racket version: 0.5.6

## Error message
```
Unable to init server: Could not connect: Connection refused
Gtk initialization failed for display ":0"
  context...:
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   do-dynamic-require5
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/platform.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   ...
```

## Additional context

I am running this in Windows Subsystem Linux 2

Unsure why the langserver needs gtk, maybe that's just racket startup stuff? I'm able to run `racket` from my terminal without issue

```
jdan@DAPHNE:~$ racket
Welcome to Racket v7.2.
> (+  3 4)
7
>
```

**Comment by Eugleo** [comment]
Hey, next week I'm getting a Windows machine to test Magic Racket on WSL. So, hold on a little longer!

**Comment by IgorMarta** [comment]
Hey @jdan, I'm experiencing a similar issue when trying to init server inside a devcontainer.

Have you managed to work around this issue?

Any insight would be highly appreciated.

**Comment by jdan** [comment]
Nope no dice yet but haven't tried anything fancy :)

**Comment by stereobooster** [comment]
related https://github.com/Eugleo/magic-racket/issues/31#issue-787807635

**Comment by Runi-c** [comment]
This issue is now tracked at https://github.com/jeapostrophe/racket-langserver/issues/45

**Comment by lopezca** [comment]
Hello!

Great plugin, thank you!

I also have this issue when trying to run it when there is no display available;
xvfb does work, but the server has to be started beforehand.

would it be possible to add a configuration option to change the command to launch the server?
that way, it can be modified to make it work with xvfb and use it as usual.

cheers!

**Comment by HugoBarreto** [comment]
Could someone provide the exact steps that you're using to run racket-langserver in WSL? 

I'm using VS Code and couldn't figure how to use xvfb in this context.

**Comment by SFurnace** [comment]
@HugoBarreto @jdan I found a workaround, please see this [https://github.com/Eugleo/magic-racket/issues/51](https://github.com/Eugleo/magic-racket/issues/51)

**Comment by Eugleo** [comment]
Closing, as there is currently a workaround and the issue itself cannot be fixed on the side of Magic Racket. I will link the workaround from the readme.

**Comment by tim-harding** [comment]
![image](https://user-images.githubusercontent.com/13814470/149213174-5ed797fe-81df-4377-bb88-38a3a6bb972d.png)
This is the configuration that works for me. I had to add `--auto-servernum` to make the server start up consistently.

**Comment by coyorkdow** [comment]
Same problem on vscode ssh to a Debian instance and magic-racket extension crashed. Using xvbf works fine to me.

> ```json
> {
>     "magicRacket.languageServer.command": "xvfb-run",
>     "magicRacket.languageServer.arguments": [
>         "--auto-servernum",
>         "racket",
>         "--lib",
>         "racket-langserver"
>     ],
> }
> ```
> 
> This is the configuration that works for me. I had to add `--auto-servernum` to make the server start up consistently.

**Comment by jaybonthius** [comment]
@tim-harding's solution also worked for me on Ubuntu, after installing `xvfb`.

**Comment by vadim-su** [comment]
Sorry, but why does the language server depend on gtk?

**Comment by jryans** [comment]
The language server depends on modules originally built for DrRacket, a GUI application. Someone could rearchitect it differently, but that hasn’t happened yet.
