### ISSUE TITLE
Can't run in vscode dev container

### ISSUE THREAD

**Issue by stereobooster** [Eugleo/magic-racket#31]
## Environment

- OS: Debian
- OS Version Debian GNU/Linux 10 (buster)
- VS Code Version: 1.52.1
- Racket version 7.9
- Racket Langserver checksum b50f8e167d0b059729d123d4e2999ffafeeaf4a1
- Magic Racket version 0.5.6

## Error message
Can't start language server

## Additional context
I'm trying to run it in vscode dev container https://github.com/stereobooster/racket-vscode-remote-development-template
racket-langserver needs xserver to work - I'm using xvbf instead.

```json
{
  "magic-racket.general.racketPath": "xvfb-run racket"
}
```

Any advice? (I also understand this can be out of scope - you can close it if this is the case)

**Comment by Eugleo** [comment]
Hey, I probably won't be able to help you, but try to go through the other issues (both open and closed, there's only a few) — I have a feeling someone else has encountered this problem as well.
