### ISSUE TITLE
Add option to turn off language server support

### ISSUE THREAD

**Issue by vanniewelt** [Eugleo/magic-racket#32]
I can't seem to make the language server working (I'm running into the same error described in #24 or jeapostrophe/racket-langserver#11).

Because of that, the error message keeps constantly popping up, which makes this extension practically unusable. The logical solution would be to fix the lang-server itself, but until that, it would be nice if there was an option to simply turn LSP support off.

I could, of course, simply switch to a different extension, but Magic Racket is still far superior to the other extensions, even without LSP – it has the best syntax highlighting and REPL integration is very convenient. Turning LSP off could be the way to go for those folks who just want to get decent syntax highlighting without any extra setup.

EDIT: I accientally marked this issue as a bug, which is incorrect. It's a feature request. Or maybe request for help, If you know any workaround.

**Comment by Eugleo** [comment]
I'm hard pressed to find time to work on this atm, but I'm more than willing to accept PRs for this issue! Let me know if you're up for it.

**Comment by vanniewelt** [comment]
I've never worked on VS Code extension before but I suppose it shouldn't be that difficult. I'll take a look at it.
