### ISSUE TITLE
User Input not working

### ISSUE THREAD

**Issue by bevo009** [Eugleo/magic-racket#35]
## Environment
- OS: WIn10 and WSL2 Ubuntu 20.04
- OS Version WIn10.0.19042 and WSL2 Ubuntu 20.04
- VS Code Version [1.52.1]
- Racket version [7.9 (win), 7.2 (wsl2)]
- Magic Racket version [0.5.7] 

## Error message
Insert a number: ; >: contract violation
;   expected: real?
;   given: #f
;   argument position: 2nd
; [,bt for context]

## Additional context
User Input seems to not work in the Magic extension
This is on Windows, and also on WSL 2 Ubuntu
The code below runs correctly in Dr Racket and Emacs
```
#lang racket

(define (inquire-user number)
  (display "Insert a number: ")
  (define guess (string->number (read-line)))
  (cond [(> number guess) (displayln "Too low") (inquire-user number)]
        [(< number guess) (displayln "Too high") (inquire-user number)]
        [else (displayln "Correct!")]))

(displayln "Guess a number between 1 and 100")
(inquire-user (random 1 101))
```

-----

Additional problems:

[Win only], the `Load File in REPL` button only opens the repl,
you have to press it again to actually load the file [works fine in ubuntu]

[Win only] Ctrl-L doesn't clear the screen (works fine in ubuntu)

[Win & Linux] The prompt appends the filename when loading a file,, which is kinda messy
Not ideal with long filenames, and not how Emacs and Dr Racket do it
I prefer the simple `>`

**Comment by Runi-c** [comment]
The error is because `read-line` does not read CRLF line endings properly by default [(default mode is `'linefeed`)](https://docs.racket-lang.org/reference/Byte_and_String_Input.html#(def._((quote._~23~25kernel)._read-line))), so it's including the CR in the number, hence causing `string->number` to return false. I don't think this is fixable on the extension side, it's up to the editor sending CRLFs (which of course it will, it's Windows).

You can fix it by specifying `'mode` of `read-line`:

```racket
(define guess (string->number (read-line (current-input-port) 'any)))
```

**Comment by Eugleo** [comment]
I agree with Runi. As per your other issues:

1. the Load File in REPL button only opens the repl: We'retracking that in #40.
2. Ctrl-L doesn't clear the screen: I'm not too familiar with Windows, but I think it's up to your shell to interpret the Ctrl+L command. Try switching to git bash, or googling how to clear screen in your particular shell. Can't be fixed on Magic Racket side, unfortunately.
3. The prompt appends the filename when loading a file: I looked at the `racket` executable documentation, but I don't see nay flags that would hide the module name from the prompt. If you find something, let me know, and we can implement it.

Seeing that all the issues you mentioned are either not fixable by Magic Racket, or tracked already, I'm closing this issue. Let me know if you have any further problems, @bevo009 .
