### ISSUE TITLE
tmLanguage version of the syntax?

### ISSUE THREAD

**Issue by jasonhan-vassar** [Eugleo/magic-racket#37]
Hi, is there any way I can build the included Racket syntax as a `.tmLanguage`? I would like to use this syntax in Sublime Text, which only supports the XML version of `.tmLanguage` and not `.tmLanguage.json`. Thanks for reading!

**Comment by Eugleo** [comment]
Hey, I’m not sure to be honest! Try to search for yaml->xml or json-> converters. You might even need to edit the results manually.

**Comment by jasonhan-vassar** [comment]
Thanks for the quick reply, I'll give that a try. Should I get started with the `racket.yaml` source or the built `racket.tmLanguage.json`?

**Comment by Eugleo** [comment]
The json files are generated from the yaml, both should be virtually identical. Depends on what will be the easiest to transition to xml (my bet is on json), but honestly, I have no idea.

**Comment by jasonhan-vassar** [comment]
Hi, would you mind trying out the conversion yourself and verifying the behavior? I am really struggling with converting the `tmLanguage.json` syntax file. I've been at it for hours and I just want a working `tmLanguage` file. When I do the conversion, the resulting XML isn't behaving the same as the original JSON, and I have no clue why. If you'd like, I can add a bounty to this, just let me know how much.

### Original
<img width="1680" alt="Screen Shot 2021-02-27 at 3 53 08 AM" src="https://user-images.githubusercontent.com/34594853/109382583-4fe5c400-78af-11eb-8d36-7c65b93af98e.png">

### Converted
<img width="1680" alt="Screen Shot 2021-02-27 at 3 52 42 AM" src="https://user-images.githubusercontent.com/34594853/109382578-3fcde480-78af-11eb-83c2-3fa67120eec7.png">
