### ISSUE TITLE
Running test submodules?

### ISSUE THREAD

**Issue by jackfirth** [Eugleo/magic-racket#39]
In DrRacket, hitting Run runs both the current module, the `main` module, and the `test` submodule. In Magic Racket it seems that the Run button runs the module and the `main` submodule, but not the `test` submodule. I'd like it to run the tests, since that's usually how I test code as I'm working on it. For context, I don't typically run the entire package's tests while developing, just in CI. Running just the tests I'm working on makes local development much faster and more seamless.

**Comment by Runi-c** [comment]
Perhaps modifying [the run command](https://github.com/Eugleo/magic-racket/blob/090ae334a9488f09e8a57048741e3a1857e5f32a/src/repl.ts#L30-L32) to send a `raco test {file}` before running it would be sufficient? It wouldn't be invisible like how DrRacket does it, so I wonder if people might find this to be unexpected behavior if it's not put in another button (Test and Run?)

**Comment by Eugleo** [comment]
You can achieve this by using VS Code tasks. The next version of Magic Racket (due today) will supply basic Run and Test tasks, which you can combine in whichever task you will want to run. The tasks will be runnable by running `Tasks: Run Task`, by using assigned keyboard shortcuts, or by using an extension like Task Runner to run them.

**Comment by jackfirth** [comment]
I've dug up some more information and have a more specific feature request. Based on [these docs](https://code.visualstudio.com/api/extension-guides/testing), there seems to be a standard Test Explorer UI built-in to VS Code that extensions can report discovered tests to. Could Magic Racket do that by default for test submodules?

**Comment by Eugleo** [comment]
Just on a quick glance it should be possible, but unfortunately I probably won't be able to add it in the near future due to time constraints. Happy to accept a PR for this, though.
