### ISSUE TITLE
"Load file in REPL" doesn't load file

### ISSUE THREAD

**Issue by circumspect** [Eugleo/magic-racket#40]
## Environment
- OS: Windows
- OS Version: Windows 10
- VS Code Version: 1.55.0
- Racket version: 8.0
- Racket Langserver checksum: 2d2aa29e195e25cd3e65cf9f32d17d6408c1140d
- Magic Racket version: 0.5.7

When I click the "Load file in REPL" button or run the command from the command palette, it launches a terminal and runs `racket` with no other arguments, and I am unable to use any names declared in the file, which suggests that the file has not been loaded.

**Comment by Runi-c** [comment]
Workaround for now is to simply click the button again. For some reason the first time you click it it just launches the REPL, subsequent clicks actually load the relevant file.

**Comment by Eugleo** [comment]
If it has been always like this, maybe it's an error on my side. I'll check the REPL-launching logic.

Btw, @Runi-c, thank you for the continuing work on the LSP! I'm following the project (as in, literally following on github) and half my emails last week were due to your PRs. Good job!

**Comment by Runi-c** [comment]
@Eugleo Thanks! Hope I can help out a bit here too after I'm done with the langserver.

**Comment by circumspect** [comment]
Having used the workaround for a while now I think I'm actually somewhat in favor of the current behavior, as it is sometimes nice to know that the REPL doesn't have anything loaded. The only issue then is that the current labeling is somewhat misleading, and there is no way for the user to know that they need to click the button again to load the file.

**Comment by Eugleo** [comment]
The button actually _does_ load the REPL _and_ the file, at least on my setup with moderately small files. Therefore, renaming the button is not a good option. The problem seems to be that sometimes the REPL doesn't finish loading when Magic Racket sends the `enter!` command to it. Until there is a way to know whether the REPL has loaded, I'm closing this issue.
