### ISSUE TITLE
Is pollen within the scope of this project?

### ISSUE THREAD

**Issue by matms** [Eugleo/magic-racket#43]
Hello,

I saw issue #16 and I seem to be having a similar problem, though possibly not exactly the same problem.

When I write `#lang pollen` as the first line, I get errors popping up every time I edit the file.

Specifically, it reports:
``
Caught exn in request "textDocument/documentSymbol"
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: #<void>
``

The context is
``
text-document.rkt:192:0: get-symbols
text-document.rkt:374:0: document-symbol
[...]
``

Is this a problem on my end, or is pollen not intended to be supported by this extension? I'm guessing this is an issue with the language server, but I'm not sure if I should open an issue _there_ instead, since maybe pollen isn't withing the scope of either project.

**Comment by Eugleo** [comment]
Better ask over at the LSP repo. I _think_ Pollen would need special treatment to work fully, which maybe indeed is beyond the current scope of the LSP, but throwing errors like this certainly isn't ok.

**Comment by Runi-c** [comment]
This should be fixed now if you run `raco pkg update racket-langserver`.

**Comment by Eugleo** [comment]
Closing this issue, please reopen if the issue persists.
