### ISSUE TITLE
Magic Racket for an intro programming course

### ISSUE THREAD

**Issue by bwbecker** [Eugleo/magic-racket#44]
## Environment
- OS: MacOS
- OS Version: Catalina
- VS Code Version: 1.55.2
- Racket version: 7.7
- Racket Langserver checksum: 2a4b446b72c069f89078c63e774117542beac917
- Magic Racket version:  0.5.7]

## Issues
Hi -- I'm investigating using VSCode + Magic Racket (instead of DrRacket) for our introductory programming course in the Fall.  I want to take advantage of VSCode's Live Share during the pandemic while physical distancing is required.

The significant impediments that I see currently (in decreasing order of importance):
1. check-expect from the teaching languages seems to be a no-op.  
2. Constructor and constant output styles.  We prefer to see "true" rather than "#t", "empty" rather than "'()", and "(list 3 4)" rather than "'(3 4)".
2. Error messages are pretty ugly (from a beginner's point of view).  Could we have a setting that automatically strips the context?
3. Code formatting (at least re-indentation).  I saw #9 and the comment about turning on the "Format on Type" functionality.  But that doesn't appear to be useful because the closing of the S-expression is supposed to trigger the re-format but closing parens are inserted automatically when you type the opening one.  So I'm not seeing this functionality triggered.

Thanks for any consideration you can give to these.

**Comment by jryans** [comment]
@bwbecker It's been a while, so I'm not sure if you're still using this extension... I'm helping out with maintaining this extension, and I'd like to see what we can do here to help. I'd also like to break down each part of this report into it's own issue where we can.

On the code formatting side, I've filed #101 and #102 to track the main issues I can see there at the moment.

For the others, are you still interested in seeing those changes made? If so, I'd like to have a bit more detail on each, like where the outputs are appearing, etc.

Thanks!

**Comment by bwbecker** [comment]
@jryans, thanks for reaching out.  We decided to go a different way and in the intervening (nearly) two years, I've lost the context of my original post.  So feel free to close it if you wish.

**Comment by jryans** [comment]
Ah okay, totally understandable. Thanks for the reply!
