### ISSUE TITLE
"Load file in REPL" not compatible with spaces in racket executable path

### ISSUE THREAD

**Issue by harry-xiaomi** [Eugleo/magic-racket#46]
## Environment
- OS: macOS
- OS Version Big Sur
- VS Code Version 1.57.0
- Racket version 8.1
  - run: `racket -v`
- Racket Langserver checksum 2a4b446b72c069f89078c63e774117542beac917
- Magic Racket version 0.5.7

## Error message
```
racket-presentations % /Applications/Racket v8.1/bin/racket
zsh: no such file or directory: /Applications/Racket
```

## Additional context
Trying to start an REPL.

---

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.

**Comment by Eugleo** [comment]
Can't test atm, but did you try escaping the spaces manually in the racket path in the settings? Like `/Applications/Racket\ v8.1/bin/racket`
