### ISSUE TITLE
Consider publishing to the Open VSX Registry

### ISSUE THREAD

**Issue by rgcv** [Eugleo/magic-racket#47]
Hey there!

First off, lovely extension.  Great to see Racket support for VSCode using LSP.  Lovely job! :+1:

As a Code OSS user, I'm afraid it saddens me not to see this extension available to me because Code OSS does not have access to Microsoft Visual Studio marketplace extensions since it would violate Microsoft's terms of use.

There is, however, an alternative open registry called [Open VSX](https://open-vsx.org).  It is an open source marketplace for VS Code extensions which Code OSS uses by default.  Seeing the extension is open source and distributed under an open source license, it seems like a fitting candidate to be published over there.

The publishing process seems familiar and straightforward, shouldn't be too much of a hassle.  Making this and many more extensions available outside the Microsoft marketplace would be pretty cool.  For some, even necessary if they're not willing to abandon purely FOSS (which Microsoft's VSCode isn't entirely, just based on Code OSS, but I'm rambling).

Any time spent caring for this issue is much appreciated. Thank you!

**Comment by Eugleo** [comment]
Hey, sure, good idea! I don't have much spare time atm, but I'll jump on it later in August. Ping me if I forget about this, please.

**Comment by rgcv** [comment]
Sure thing! No problem, I will if I don't forget to myself.

**Comment by Eugleo** [comment]
Hey, I finally got to do this! Better late than never, am I right? [See for yourself](https://open-vsx.org/extension/evzen-wybitul/magic-racket). Have a happy new year!
