### ISSUE TITLE
highlighting is incorrect with literal `#\"`

### ISSUE THREAD

**Issue by dannypsnl** [Eugleo/magic-racket#48]
## Environment
- OS: MacOS
- OS Version BigSur
- VS Code Version 1.58.2
- Racket version 8.2
  - run: `racket -v`
- Racket Langserver checksum 6d01f910dfd332d3bcaeef176162de80931b324a
  - run: `raco pkg show --full-checksum racket-langserver`
- Magic Racket version 0.5.7 

## Additional Context

<img width="745" alt="圖片" src="https://user-images.githubusercontent.com/22004511/127699916-2d02d1fc-7906-4f5f-b7ca-b0c5596f2891.png">

**Comment by dannypsnl** [comment]
@Eugleo would you mind giving some hints?

**Comment by Eugleo** [comment]
Sure. In general, it might be useful to look at the `Developer: Inspect Editor Tokens and Scopes` command. If you're not sure what a token and a scope is, I recommend giving [this article in VSC docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) a look.

I found out that the character literals actually work ok when used at top-level, and the causes are different in each case that you presented.

## First problem

The problem in @jryans code is the `#rx` string in which the first `\"` isn't properly escaped. To fix this, we can add the following pattern to the `regexp-string` pattern:

```json
"patterns": [
  {
    "include": "#escape-char-base"
  }
]
```

The same piece of code is in byte strings and normal strings. I'm not sure why I haven't added support for escape characters into regex strings in the first place — maybe I just forgot to do so. Anyway, once I add this, the highlighting in this case is fixed:

<img width="569" alt="CleanShot 2021-12-26 at 10 06 48@2x" src="https://user-images.githubusercontent.com/21257632/147403728-c965c23c-5552-439f-ab45-8fc72dc835be.png">

## Second problem

As for the original problem, I have no idea what's causing it. On my machine, it works fine:

<img width="439" alt="CleanShot 2021-12-26 at 10 11 12@2x" src="https://user-images.githubusercontent.com/21257632/147403826-d601ed9f-bb19-4c0b-b18b-5ea48f2f6026.png">

I'm also on MacOS, Racket 8.3, Magic Racket 5.7.1. Please make sure to update your magic racket to the latest version, and also make sure you only have magic racket a no other racket extension installed. If the problem persists, please send me the whole file and also tell me what does the token and scope command show for that problematic piece of code.

**Comment by Eugleo** [comment]
In the meantime, I will close this issue because I'm unable to reproduce it.

**Comment by dannypsnl** [comment]
My problem get fixed with Magic-Racket 5.8, thanks
