### ISSUE TITLE
REPL printing "(enter! (file ...))" after exiting racket

### ISSUE THREAD

**Issue by EnumType** [Eugleo/magic-racket#54]
## Environment
- OS: Windows 10
- VS Code Version 1.60.1
- Racket version 8.2
  - run: `racket -v`
- Racket Langserver checksum 962d9a337631ae0713bbdec3b4a1b35d6ff65294
  - run: `raco pkg show --full-checksum racket-langserver`
- Magic Racket version 0.5.8

## Error message
```PS C:\path> racket
Welcome to Racket v8.2 [bc].
> (exit)
PS C:\path> (enter! (file "c:/path/test.rkt"))
+ (enter! (file "c:/Users/Anfinn/Documents/Informatik/test.rkt"))
+          ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

## Additional context
After I run the .rkt file in REPL nothing happened. I typed `(exit)` and racket exits. Then the console types the ´(enter!)´ thing..

---

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.

**Comment by Eugleo** [comment]
Should be fixed in the new version. Lmk.
