### ISSUE TITLE
Make error trace an option

### ISSUE THREAD

**Issue by rongcuid** [Eugleo/magic-racket#55]
## Environment
- OS: Pop OS 20.04

- VS Code Version 1.60.2
- Racket version 8.2

- Racket Langserver checksum 962d9a337631ae0713bbdec3b4a1b35d6ff65294
- Magic Racket version 0.5.6

## Enhancement

It would be great to add an option to easily enable `errortrace`. I currently set the REPLRacket path to `racket -il errortrace -l xrepl`, but it would be good to give an option for better discoverability.

**Comment by Eugleo** [comment]
Hey, this is a good idea. Would you be willing to make a PR for it? I'd happily accept something along the lines of 

1. Make a new setting that will be a list of packages to load in the REPL (which will the just get pasted after the real path with `-l`s prefixed).
2. After launching Magic Racket for the first time, show a notification asking the user if they want to enable `errortrace` in the REPL (recommended), or not. If so, set the new setting to be `["errortrace"]`.

This way, most users will probably go the recommended route.

**Comment by Eugleo** [comment]
I've added the possibility to edit arguments that are passed when creating the REPL. Should be enough for now.
