### ISSUE TITLE
Multiline comments not working?

### ISSUE THREAD

**Issue by jestarray** [Eugleo/magic-racket#56]
## Environment
- OS: Arch Linux
- VS Code Version 1.62.1
- Racket version 8.3
- Racket Langserver checksum 490c72ad7ef35878744c47c8235fabb810f9ab3c
- Magic Racket version v0.5.8

![image](https://user-images.githubusercontent.com/34615798/142711475-e0f25545-ef18-442e-a0a0-acd3453ba331.png)

**Comment by Eugleo** [comment]
Sorry, forgot to get back to you. Anyway, works fine on my end (I'm on MacOS, though it shouldn't make any difference).

<img width="221" alt="CleanShot 2021-11-28 at 08 45 23@2x" src="https://user-images.githubusercontent.com/21257632/143734165-8bb56693-0e01-4d17-a271-820ac25290fe.png">


Make sure you have "Racket" selected as the language in the bottom left in VS Code, and that you don't have any other Racket extensions besides Magic Racket. I can't think of anything else that could be causing this.
