### ISSUE TITLE
Escape chars aren't supported in regexp byte strings

### ISSUE THREAD

**Issue by shocoman** [Eugleo/magic-racket#59]
Here is example
![image](https://user-images.githubusercontent.com/8329446/147559009-c266e880-ebe6-49f8-9bd3-2c8578f02e01.png)

**Comment by Eugleo** [comment]
Hey, should be fixed in the last release (v0.6.0). Let me know

**Comment by shocoman** [comment]
Well, regular regexps are fixed, indeed. But not the byte regexps. At least as I see it
![image](https://user-images.githubusercontent.com/8329446/147564252-bbbda995-b268-4b5e-bdd9-e460d33d956a.png)

**Comment by Eugleo** [comment]
Ah, you're right, sorry, I missed that in your original screenshot.

**Comment by Eugleo** [comment]
@shocoman pushed v0.6.1 to fix this issue. Thanks for reporting!
