### ISSUE TITLE
support "workspace/willRenameFiles" request

### ISSUE THREAD

**Issue by dannypsnl** [Eugleo/magic-racket#60]
This will help the language server be able to send back **to update** edits when a file gets renamed.

Suppose we have `a.rkt`, `c.rkt` where `c` requires `a`, now we rename `a.rkt` to `b.rkt`. A language server supports this will return things like

```racket
(list (replace "c.rkt" (position ...) #:with-text "b.rkt")
      (replace ...) ; if more place requires `a.rkt`
      ...)
```

**Comment by Eugleo** [comment]
Is this something I can do only in Magic Racket, or do we need something implemented in the language server, first? If the latter, please close this issue here and open a similar one on the langserver repo.

**Comment by dannypsnl** [comment]
I think needs implement from server first
