### ISSUE TITLE
"Run file in terminal" doesn't work on Windows due to a wrong path

### ISSUE THREAD

**Issue by shocoman** [Eugleo/magic-racket#63]
Demo: 

https://user-images.githubusercontent.com/8329446/147846617-fdc42c4f-d67c-4605-a735-5f6c5d41d4bd.mp4

I believe the problem is in "shell-quote" library that is used here. It escapes some characters including `:`, but on Windows `C:` is a completely valid disk name. 
Here is an example of `quote` from the console:
![image](https://user-images.githubusercontent.com/8329446/147846515-8b4d4663-73f6-4a72-9395-87fd172bcd48.png)

**Comment by vedangnaik** [comment]
I have the same issue. 

These are the versions I'm running, if that's useful:

> Version: 1.63.2 (user setup)
> Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
> Date: 2021-12-15T09:40:02.816Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19043
