### ISSUE TITLE
expand selection has no effect

### ISSUE THREAD

**Issue by nikomatsakis** [Eugleo/magic-racket#74]
## Environment
- OS:macos + linux
- VS Code Version: 1.65.1
- Racket version: 7.9
- Racket Langserver checksum 962d9a337631ae0713bbdec3b4a1b35d6ff65294
- Magic Racket version 0.6.4

## Error message

Running expand selection has no effect anywhere

## Additional context

It started when I upgraded VSCode on my liinux machine to the latest version -- it worked great before that!

**Comment by spdegabrielle** [comment]
7.9 is an old version of Racket. 
Does the bug happen with the current version? 
8.4 is available at https://download.racket-lang.org/

**Comment by nikomatsakis** [comment]
I'll check :)

**Comment by nikomatsakis** [comment]
Sadly, no. I've installed 8.4 and have the same problem.

**Comment by nikomatsakis** [comment]
So, I don't know *why*, but it seems to work again! Closing.
