### ISSUE TITLE
Highlighting Issue with Escape Character #\

### ISSUE THREAD

**Issue by mfteuscher** [Eugleo/magic-racket#80]
When I use the escape character #\ it generally works, but if I use the escape character with parenthesizes like this `#\(` or `#\)` it reads it as an actual open or close parentheses and says VS Code highlights some ending parentheses as red because it can't find the matching ones, even though it complies right.

**Comment by xiaoyu2006** [comment]
Any updates 👀 ?

**Comment by jryans** [comment]
Presumably if there were updates, they would appear here. I would encourage those facing this to attempt a contribution to fix it.

**Comment by xiaoyu2006** [comment]
@jryans Patch submitted 🚀
