### ISSUE TITLE
Autocomplete doesn't work for #lang errortrace racket

### ISSUE THREAD

**Issue by tehkonst** [Eugleo/magic-racket#86]
## Environment
- OS: Linux Ubuntu 20.04
- VS Code Version 1.73.1
- Racket version 8.6
- Racket Langserver checksum ad7c0c958968d526c1b27c4d40959d737fd81111
- Magic Racket version 0.6.4
---

If I specify the first line for language as `#lang errortrace racket` the autocomplete stop working.
And without errotrace it's impossible to find where errors occur.

**Comment by Eugleo** [comment]
AFAIK this is a problem with the langserver, not much I can do here unfortunately 😕
