### ISSUE TITLE
Cannot connect to racket-langserver

### ISSUE THREAD

**Issue by eroosendahl** [Eugleo/magic-racket#87]
## Environment
- OS: [Windows 10 Home]
- OS Version [22H2]
- VS Code Version [1.73.1]
- Racket version [8.7]
- Racket Langserver checksum:
  - raco pkg show --full-checksum racket-langserver
    Installation-wide:
    [none]
    User-specific for installation "8.7":
    [none]
- Magic Racket version [0.6.4] 

## Error message
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\eroos\AppData\Roaming\Racket\8.7\collects
   C:\Program Files\Racket\collects\
   ... [172 additional linked and package directories]
[Info  - 6:56:02 PM] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\eroos\AppData\Roaming\Racket\8.7\collects
   C:\Program Files\Racket\collects\
   ... [172 additional linked and package directories]
[Info  - 6:56:02 PM] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\eroos\AppData\Roaming\Racket\8.7\collects
   C:\Program Files\Racket\collects\
   ... [172 additional linked and package directories]
[Info  - 6:56:02 PM] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\eroos\AppData\Roaming\Racket\8.7\collects
   C:\Program Files\Racket\collects\
   ... [172 additional linked and package directories]
[Info  - 6:56:02 PM] Connection to server got closed. Server will restart.
standard-module-name-resolver: collection not found
  for module path: (lib "racket-langserver")
  collection: "racket-langserver"
  in collection directories:
   C:\Users\eroos\AppData\Roaming\Racket\8.7\collects
   C:\Program Files\Racket\collects\
   ... [172 additional linked and package directories]
[Error - 6:56:03 PM] Connection to server got closed. Server will not be restarted.

## Additional context
My apologies if this is trivial or my mistake, but I cannot figure out myself why I can't connect to langserver.  I've used this extension on a different windows machine and did not have this issue.  
I also recognize my "Racket Language checksum" seems perhaps wrong, I don't know what that is or how it would have become "none", when the expected value was very different.  If that is also my fault, sorry again.
I can run racket code on vscode just fine, but have no langserver features.

Hope this was submitted properly, if it wasn't let me know and I will try to fix it.

**Comment by tehkonst** [comment]
Install langserver:
raco pkg install racket-langserver

**Comment by eroosendahl** [comment]
raco pkg install racket-langserver
raco pkg install: package is already installed
  package: racket-langserver

**Comment by eroosendahl** [comment]
raco pkg update racket-langserver
Resolving "racket-langserver" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "racket-langserver" via https://pkgs.racket-lang.org
No updates available

**Comment by eroosendahl** [comment]
Ahh i'd done those commands on WSL.  My mistake. doing them on normal cmd solved this issue, thank you.
