### ISSUE TITLE
Hover failed

### ISSUE THREAD

**Issue by ANOLASC** [Eugleo/magic-racket#88]
## Environment
- OS: Windows 11
- OS Version 22621.819
- VS Code Version 1.73.1
- Racket version v8.6
  - run: `racket -v`
- Racket Langserver checksum 66641495b9723e44c8d2a915aca052951fca3d98
  - run: `raco pkg show --full-checksum racket-langserver`
- Magic Racket version v0.6.4 

## Error message
Caught exn in request "textDocument/codeAction"
hash-ref: no value found for key
  key: 'file:///code/test.rkt
  context...:
   xxx\Racket\8.6\pkgs\racket-langserver\text-document.rkt:153:0: code-action
   xxx\Racket\collects\racket\contract\private\arrow-val-first.rkt:486:18
   xxx\Racket\8.6\pkgs\racket-langserver\methods.rkt:26:0: process-message
   xxx\Racket\collects\racket\contract\private\arrow-val-first.rkt:486:18
   xxx\Racket\8.6\pkgs\racket-langserver\main.rkt:54:2: consume

[Error - 21:10:22] Request textDocument/codeAction failed.
  Message: internal error in method "textDocument/codeAction"
  Code: -32603 

## Additional context

---

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.
[log.txt](https://github.com/Eugleo/magic-racket/files/10132664/log.txt)

**Comment by jryans** [comment]
@ANOLASC Thanks for filing this issue a while back. Are you able to share the source file you were working with that triggers this? I think it will be quite a bit easier to diagnose with that.
