### ISSUE TITLE
"Load file in REPL" not works

### ISSUE THREAD

**Issue by chemPolonium** [Eugleo/magic-racket#94]
## Environment
- OS Windows 11
- OS Version 22621.900
- VS Code Version 1.73.1
- Racket version v8.7
- Racket Langserver checksum c7215111e86f262e1765ace13ec2c0f81d06f144
- Magic Racket version 0.6.4

## Error message
enter!: not a module path or #f

## Additional context
If click "Load file in REPL" the first time, this error will occur. The second time (with REPL open) click "Load file in REPL" will work fine.

The whole terminal output:
```
PS C:\Users\chemp\OneDrive\Source\Racket\SICP> racket --repl --eval '(enter! (file \"c:/Users/chemp/OneDrive/Source/Racket/SICP/e2-89.rkt\"))'
Welcome to Racket v8.7 [cs].
enter!: not a module path or #f
  at: (file |"c:/Users/chemp/OneDrive/Source/Racket/SICP/e2-89.rkt"|)
  in: (enter! (file |"c:/Users/chemp/OneDrive/Source/Racket/SICP/e2-89.rkt"|))
  context...:
   C:\Users\chemp\scoop\apps\racket\current\collects\racket\enter.rkt:10:0
```

I tried this in powershell and it works
```
PS C:\Users\chemp\OneDrive\Source\Racket\SICP> racket --repl --eval '(enter! (file "c:/Users/chemp/OneDrive/Source/Racket/SICP/e2-89.rkt"))'
```

Maybe it's because a redundant `\`.

**Comment by anryoshi** [comment]
Looks like there is a difference between PS versions.
[Behavior](https://github.com/Eugleo/magic-racket/blob/master/src/repl.ts#L89) works with PS version 5.1, but fails with 7.3.1 (probably for all versions >=7).
At the same time [this fragment](https://github.com/Eugleo/magic-racket/blob/master/src/repl.ts#L91) works with modern PS versions.
Probably matching should be adjusted with respect of version.

**Comment by jryans** [comment]
This should now be fixed by https://github.com/Eugleo/magic-racket/pull/110.
