### ISSUE TITLE
No run icons  in the top right corner of my editor on Windows

### ISSUE THREAD

**Issue by Tom89757** [Eugleo/magic-racket#96]
I'm not sure if I am asking a stupid question, but I can't solve it by myself. After I install Magic Racket extension in VSCode, everything works well but no run icons in the top right corner of my VSCode on Windows 10.
Here is the window screenshot from official site:
![](https://raw.githubusercontent.com/Tom89757/ImageHost/main/hexo/20221203231458.png)
Here is my window screenshot:
![](https://raw.githubusercontent.com/Tom89757/ImageHost/main/hexo/20221203231431.png)
My environment is:
- VSCode: 1.73.1
- Magic Racket: v0.6.4

**Comment by Tom89757** [comment]
I have found what the problem is. It's because my VSCode autodetects my program as Scheme, after I manually change it to Racket the buttons appears:
![](https://raw.githubusercontent.com/Tom89757/ImageHost/main/hexo/20221204001620.png)

**Comment by Eugleo** [comment]
That's weird, I think the lang recognitions should work fine with Magic Racket. Maybe there's a scheme plugin that takes precedence over Magic Racket and "claims" a rkt file?
