### ISSUE TITLE
Cant run it

### ISSUE THREAD

**Issue by sLizzard1234** [Eugleo/magic-racket#98]
I am on the latest versions of vs code and racket. 
I installed Racket and the magic racket extension. I also did everything as sad in the documentation e.g. installing and updating the langserver, but I  still get an error when i want to run a program or even start it. 

Error Msg.
Starting it: 

Starting client failed
Launching server using command racket failed. 

Running a program:
-- i had to translate so 
-- it has to be something like this:

Racket is not part of the cmdlet

Please help me i really hate the Dr.Racket IDE... it drives me nuts.

**Comment by devil0947** [comment]
this plugin is complete garbage

**Comment by Eugleo** [comment]
Hey @sLizzard1234, please add some information that could be used to debug this problem. A good starting point would be the REPORT A BUG issue template:

```
- OS: [e.g. MacOS]
- OS Version [e.g. Catalina]
- VS Code Version [e.g. 1.46.1]
- Racket version [e.g. 7.7]
  - run: `racket -v`
- Racket Langserver checksum [e.g. 64c1827548089c97c56a53a90ef3d569deb0e6c2]
  - run: `raco pkg show --full-checksum racket-langserver`
- Magic Racket version [e.g. 0.5.6] 

# How can we reproduce the bug

# What is the expected behaviour
```

**Comment by Eugleo** [comment]
Specifically, try running `racket -l racket-langserver` and report back.

**Comment by jryans** [comment]
We haven't heard back here in a while, so for now I am going to close this issue. Feel free to reopen or file a new issue if you are still having trouble.
